#!/usr/bin/env python

from flask import Flask
from flask import render_template, send_from_directory
app = Flask(__name__, static_folder='static')

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/<path:filename>')
def send_file(filename):
    print(filename)
    return send_from_directory(app.static_folder, filename)

app.run(host='0.0.0.0', port=12000)
